import {createHmac,timingSafeEqual} from 'node:crypto';import {NextResponse} from 'next/server';import {evaluateRisk} from '@/lib/risk/engine';import {supabaseAdmin} from '@/lib/supabase/admin';import {sendWhatsApp} from '@/lib/whatsapp/send';
export const runtime='nodejs';
function validSignature(raw:string,header:string|null){const secret=process.env.META_APP_SECRET;if(!secret||!header?.startsWith('sha256='))return false;const expected='sha256='+createHmac('sha256',secret).update(raw).digest('hex');const a=Buffer.from(expected),b=Buffer.from(header);return a.length===b.length&&timingSafeEqual(a,b)}
export async function GET(req:Request){const u=new URL(req.url),mode=u.searchParams.get('hub.mode'),token=u.searchParams.get('hub.verify_token'),challenge=u.searchParams.get('hub.challenge');if(mode==='subscribe'&&token===process.env.WHATSAPP_VERIFY_TOKEN)return new Response(challenge||'',{status:200});return new Response('Forbidden',{status:403})}
export async function POST(req:Request){const raw=await req.text();if(!validSignature(raw,req.headers.get('x-hub-signature-256')))return new Response('Invalid signature',{status:401});const payload=JSON.parse(raw);const msg=payload?.entry?.[0]?.changes?.[0]?.value?.messages?.[0];if(!msg)return NextResponse.json({ok:true,ignored:true});const from=msg.from as string;const text=msg.text?.body||'';const location=msg.location;const db=supabaseAdmin();
 const exists=await db.from('messages').select('id').eq('external_message_id',msg.id).maybeSingle();if(exists.data)return NextResponse.json({ok:true,duplicate:true});
 let {data:conv}=await db.from('conversations').select('id,recurrence_count').eq('wa_user_id',from).eq('status','open').maybeSingle();if(!conv){const created=await db.from('conversations').insert({wa_user_id:from,status:'open'}).select('id,recurrence_count').single();conv=created.data}if(!conv)return NextResponse.json({error:'conversation_persistence_failed'},{status:500});
 await db.from('messages').insert({conversation_id:conv.id,external_message_id:msg.id,direction:'inbound',message_type:location?'location':'text',content:text||null,metadata:location||{}});await db.from('conversations').update({updated_at:new Date().toISOString()}).eq('id',conv.id);
 if(location){await db.from('locations').insert({conversation_id:conv.id,latitude:location.latitude,longitude:location.longitude,source:'whatsapp'});return NextResponse.json({ok:true})}
 const risk=evaluateRisk(text,conv.recurrence_count||0);await db.from('risk_events').insert({conversation_id:conv.id,level:risk.level,score:risk.score,triggers:risk.triggers,categories:risk.categories,source_text:text});
 let reply='Estoy aquí contigo. Podemos ir paso a paso. ¿Te sientes segura en este momento?';if(risk.level==='medium')reply='Lo que cuentas merece atención. Si quieres, podemos revisar juntas qué está pasando y pensar en una red de apoyo segura.';if(risk.level==='high')reply='Lo que describes puede ser una situación de riesgo. Quiero ayudarte a conectarte con una persona de apoyo. ¿Es seguro continuar hablando?';if(risk.level==='critical')reply='Estoy contigo. Si puedes hacerlo sin ponerte en mayor riesgo, comparte tu ubicación por WhatsApp. Prepararé el escalamiento para atención humana conforme al protocolo.';
 const sent=await sendWhatsApp(from,reply).catch(()=>null);await db.from('messages').insert({conversation_id:conv.id,direction:'outbound',message_type:'text',content:reply,metadata:{risk_level:risk.level,provider_response:sent}});if(risk.requiresHuman)await db.from('alerts').insert({conversation_id:conv.id,alert_type:'operator',status:'pending',priority:risk.level,payload:{risk}});return NextResponse.json({ok:true,risk:risk.level})}
