const features=[
 ['Detección temprana','Identifica señales de violencia psicológica, económica, social, sexual o física mediante reglas auditables.'],
 ['Escalamiento seguro','Prioriza el caso y permite transferencia a operadora humana y protocolos institucionales autorizados.'],
 ['Ubicación con consentimiento','Solicita ubicación cuando el protocolo lo requiere y registra consentimiento y trazabilidad.'],
 ['Panel institucional','Casos priorizados, semáforo de riesgo, seguimiento, bitácora y métricas para operación municipal.'],
 ['Modo discreto','Conversación breve, neutral y configurable para reducir exposición cuando el teléfono puede ser observado.'],
 ['Auditoría completa','Cada alerta y cambio de estado queda registrado para supervisión institucional y mejora continua.']
];
export default function Home(){return <>
<header className="wrap"><nav className="nav"><div className="brand">VioletaBot</div><div className="navlinks"><a href="#solucion">Solución</a><a href="#instituciones">Instituciones</a><a href="#seguridad">Seguridad</a><a className="btn primary" href="/admin/login">Acceso institucional</a></div></nav></header>
<main><section className="hero"><div className="wrap heroGrid"><div><div className="eyebrow">Tecnología pública con enfoque humano</div><h1>Una red de apoyo que cabe en WhatsApp.</h1><p>VioletaBot ayuda a municipios e instituciones a ofrecer un primer canal discreto de acompañamiento, detectar señales de violencia y escalar casos de riesgo mediante protocolos claros, humanos y auditables.</p><div className="actions"><a className="btn primary" href="#instituciones">Conocer el MVP</a><a className="btn secondary" href="#seguridad">Ver modelo de seguridad</a></div></div><div className="phone"><div className="screen"><div className="chathead">Violeta 💜</div><div className="bubble bot">Hola, amiga. Antes de seguir: ¿es seguro hablar en este momento?</div><div className="bubble user">Sí, puedo hablar.</div><div className="bubble bot">Estoy aquí para escucharte. Podemos ir poco a poco y sin juzgarte.</div><div className="bubble user">Tengo miedo. Me amenazó.</div><div className="bubble panic"><strong>Protocolo de atención</strong><br/>El sistema detecta una señal de riesgo, reduce la conversación a pasos claros y prepara el escalamiento conforme al protocolo institucional.</div></div></div></div></section>
<section id="solucion" className="section"><div className="wrap"><div className="eyebrow">Capacidades</div><h2>Diseñado para intervenir temprano, no para improvisar en una crisis.</h2><p className="lead">El MVP combina reglas determinísticas, contexto conversacional, historial de reincidencia y supervisión humana. La IA puede apoyar la comprensión del lenguaje, pero no toma por sí sola decisiones críticas.</p><div className="grid3">{features.map(([t,d],i)=><article className="card" key={t}><div className="icon">{i+1}</div><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
<section id="instituciones" className="section band"><div className="wrap"><div className="eyebrow">Modelo institucional adaptable</div><h2>Un mismo núcleo, configurable para cada municipio o estado.</h2><p className="lead">Puede operar desde un Instituto Municipal de las Mujeres, una Dirección de Seguridad Pública, un centro de atención o una coordinación interinstitucional. Los contactos, niveles de escalamiento, mensajes, horarios y protocolos se parametrizan por organización.</p><div className="metrics"><div className="metric"><strong>24/7</strong>Canal automatizado de primera atención</div><div className="metric"><strong>5</strong>Niveles de clasificación de riesgo</div><div className="metric"><strong>100%</strong>Eventos críticos auditables</div><div className="metric"><strong>1</strong>Panel para seguimiento institucional</div></div></div></section>
<section id="seguridad" className="section"><div className="wrap"><div className="eyebrow">Seguridad por diseño</div><h2>La prioridad no es “responder bonito”; es actuar de forma predecible y trazable.</h2><div className="grid3"><article className="card"><h3>Reglas antes que IA</h3><p>Comandos críticos, scoring y escalamiento viven en código versionado y pueden auditarse.</p></article><article className="card"><h3>Datos mínimos</h3><p>La arquitectura evita recolectar información sensible que no sea necesaria para la atención.</p></article><article className="card"><h3>Autoridad bajo protocolo</h3><p>El despacho a policía permanece deshabilitado hasta existir convenio, reglas operativas y autorización institucional verificadas.</p></article></div></div></section></main>
<footer className="footer"><div className="wrap"><strong>VioletaBot</strong> · MVP institucional · Acompañamiento inicial y escalamiento seguro. No sustituye atención psicológica, médica, jurídica ni de emergencia.</div></footer></>}
