create extension if not exists pgcrypto;
do $$ begin create type public.risk_level as enum ('none','low','medium','high','critical'); exception when duplicate_object then null; end $$;
do $$ begin create type public.case_status as enum ('open','in_review','closed'); exception when duplicate_object then null; end $$;
create table if not exists public.organizations(id uuid primary key default gen_random_uuid(),name text not null,slug text unique not null,organization_type text not null default 'municipality',created_at timestamptz not null default now());
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,organization_id uuid references public.organizations(id),full_name text,role text not null default 'operator' check(role in('admin','supervisor','operator','auditor')),created_at timestamptz not null default now());
create table if not exists public.conversations(id uuid primary key default gen_random_uuid(),organization_id uuid references public.organizations(id),wa_user_id text not null,status public.case_status not null default 'open',recurrence_count int not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists conversations_wa_open_idx on public.conversations(wa_user_id,status);
create table if not exists public.messages(id bigint generated always as identity primary key,conversation_id uuid not null references public.conversations(id) on delete cascade,direction text not null check(direction in('inbound','outbound')),external_message_id text unique,message_type text not null default 'text',content text,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table if not exists public.risk_events(id bigint generated always as identity primary key,conversation_id uuid not null references public.conversations(id) on delete cascade,level public.risk_level not null,score int not null check(score between 0 and 100),triggers text[] not null default '{}',categories text[] not null default '{}',source_text text,created_at timestamptz not null default now());
create table if not exists public.alerts(id uuid primary key default gen_random_uuid(),conversation_id uuid not null references public.conversations(id) on delete cascade,alert_type text not null check(alert_type in('trusted_contact','operator','authority')),status text not null default 'pending' check(status in('pending','acknowledged','sent','failed','cancelled')),priority public.risk_level not null,payload jsonb not null default '{}'::jsonb,acknowledged_by uuid references auth.users(id),created_at timestamptz not null default now(),acknowledged_at timestamptz);
create table if not exists public.locations(id bigint generated always as identity primary key,conversation_id uuid not null references public.conversations(id) on delete cascade,latitude double precision not null,longitude double precision not null,source text not null default 'whatsapp',created_at timestamptz not null default now());
create table if not exists public.consents(id bigint generated always as identity primary key,conversation_id uuid not null references public.conversations(id) on delete cascade,consent_type text not null,granted boolean not null,evidence jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table if not exists public.audit_logs(id bigint generated always as identity primary key,organization_id uuid references public.organizations(id),actor_id uuid references auth.users(id),action text not null,entity_type text not null,entity_id text,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());

alter table public.organizations enable row level security;alter table public.profiles enable row level security;alter table public.conversations enable row level security;alter table public.messages enable row level security;alter table public.risk_events enable row level security;alter table public.alerts enable row level security;alter table public.locations enable row level security;alter table public.consents enable row level security;alter table public.audit_logs enable row level security;

create policy "profiles_self_read" on public.profiles for select to authenticated using ((select auth.uid())=id);
create policy "org_members_read_conversations" on public.conversations for select to authenticated using (organization_id=(select organization_id from public.profiles where id=(select auth.uid())));
create policy "org_members_read_messages" on public.messages for select to authenticated using (exists(select 1 from public.conversations c join public.profiles p on p.organization_id=c.organization_id where c.id=messages.conversation_id and p.id=(select auth.uid())));
create policy "org_members_read_risk" on public.risk_events for select to authenticated using (exists(select 1 from public.conversations c join public.profiles p on p.organization_id=c.organization_id where c.id=risk_events.conversation_id and p.id=(select auth.uid())));
create policy "org_members_read_alerts" on public.alerts for select to authenticated using (exists(select 1 from public.conversations c join public.profiles p on p.organization_id=c.organization_id where c.id=alerts.conversation_id and p.id=(select auth.uid())));
create policy "org_members_read_locations" on public.locations for select to authenticated using (exists(select 1 from public.conversations c join public.profiles p on p.organization_id=c.organization_id where c.id=locations.conversation_id and p.id=(select auth.uid())));
create policy "org_members_read_consents" on public.consents for select to authenticated using (exists(select 1 from public.conversations c join public.profiles p on p.organization_id=c.organization_id where c.id=consents.conversation_id and p.id=(select auth.uid())));
create policy "org_members_read_audit" on public.audit_logs for select to authenticated using (organization_id=(select organization_id from public.profiles where id=(select auth.uid())));

revoke all on all tables in schema public from anon;
grant select on public.profiles,public.conversations,public.messages,public.risk_events,public.alerts,public.locations,public.consents,public.audit_logs to authenticated;
